- name: copy the zip file
  hosts: all
  become: yes
  tasks:
    - name: copy zip file to remote server
      copy:
        src: /var/lib/jenkins/workspace/mypipe1/workbench/my-app-1.0-SNAPSHOT.jar.zip
        dest: /opt/tomcat/webapps
        owner: tomcat
        group: tomcat
